import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, relative } from 'node:path';
import type { DetoxConfig } from '../compiler/dtx/resolve.js';
import { generateTsShim, generateElementInterface } from './shim.js';

export interface ShimEntry {
  /** Dotted specifier, e.g. "pages.Login". */
  spec: string;
  path: string;
  source: string;
}

function walk(dir: string, exts: string[], out: string[]): void {
  if (!existsSync(dir)) return;
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const full = join(dir, name);
    const info = statSync(full);
    if (info.isDirectory()) walk(full, exts, out);
    else if (exts.some((e) => full.endsWith(e))) out.push(full);
  }
}

/** Discovers every `.dtx`/`.md` under the config's include roots and its dotted spec. */
export function collectShimEntries(config: DetoxConfig, configRoot: string): ShimEntry[] {
  const roots = config.resolve.includes.length
    ? config.resolve.includes.map((inc) => (isAbsolute(inc) ? inc : join(configRoot, inc)))
    : [configRoot];
  const exts = config.resolve.extensions;
  const entries: ShimEntry[] = [];
  const seen = new Set<string>();
  for (const root of roots) {
    const files: string[] = [];
    walk(root, exts, files);
    for (const file of files) {
      let rel = relative(root, file).replace(/\\/g, '/');
      for (const e of exts) if (rel.endsWith(e)) rel = rel.slice(0, -e.length);
      // Package form dir/module → dir
      rel = rel.replace(/\/module$/, '');
      const spec = rel.split('/').join('.');
      if (seen.has(spec)) continue;
      seen.add(spec);
      entries.push({ spec, path: file, source: readFileSync(file, 'utf8') });
    }
  }
  return entries;
}

/** Builds the ambient-module declarations for dotted imports. */
export function buildShimsFile(entries: ShimEntry[]): string {
  const blocks = entries.map((e) => {
    const body = generateTsShim(e.path, e.source, { ambient: true })
      .split('\n')
      .filter((l) => !l.startsWith('//'))
      .map((l) => (l ? `  ${l}` : l))
      .join('\n');
    return `declare module ${JSON.stringify(e.spec)} {\n${body}}`;
  });
  // Element interfaces (host methods from `actions`) + HTMLElementTagNameMap,
  // emitted at top level so querySelector("<tag>") is typed globally.
  const elems = entries
    .map((e) => generateElementInterface(e.path, e.source)?.decl)
    .filter(Boolean);
  const header = '// AUTO-GENERATED by uidetox/vite. Do not edit.\n// Add ".uidetox/dtx-shims.d.ts" to your tsconfig "include".\n';
  return `${header}${blocks.join('\n\n')}\n\n${elems.join('\n\n')}\n`;
}

/** Writes `<root>/.uidetox/dtx-shims.d.ts`. Returns the path written. */
export function writeShims(root: string, config: DetoxConfig, configRoot: string): string {
  const entries = collectShimEntries(config, configRoot);
  const dir = join(root, '.uidetox');
  mkdirSync(dir, { recursive: true });
  const out = join(dir, 'dtx-shims.d.ts');
  writeFileSync(out, buildShimsFile(entries), 'utf8');
  return out;
}
